<MyLayout>
	BoxLayout:
		orientation: 'vertical'
		size: (root.width, root.height)

		Accordion:
			orientation: 'vertical'

			AccordionItem:
				title: 'Panel 1'
				Label:
					text: 'Hello World'
					font_size: 32
			AccordionItem:
				title: 'Panel 2'
				Label:
					text: "What's Your Name?"
					font_size: 32
			AccordionItem:
				title: 'Panel 3'
				Image:
					source: "D:/kivy/kivy.2.1.0/images/dp.jpg"