<MyLayout>
	BoxLayout:
		orientation: 'horizontal'
		size: (root.width, root.height)

		Carousel:
			direction: "right"


			Image:
				source: "D:\kivy\kivy.2.1.0\images\dp.jpg"

			Image:
				source: "D:\kivy\kivy.2.1.0\images\kaneki.png"

			Image:
				source: "D:\kivy\kivy.2.1.0\images\megumin.png"
			
			#from internet doesn't work
			#Image:
			#	source: "https://www.anime-planet.com/images/characters/fuu-naruto-shippuden-66908.jpg?t=1421642105"

